### ISSUE TITLE
Requires

### ISSUE THREAD

**Issue by lebogan** [I3oris/ic#9]
Is it possible to require a local file from within ic? This doesn't work, the file does exist:
```
ic(1.5.1):001> require "./myclass.cr"                                                           
In <top-level>:1:1

 1 | require "./myclass.cr"
     ^
Error: can't find file './myclass.cr'

ic(1.5.1):002> 
```
Thanks

**Comment by I3oris** [comment]
Hello @lebogan, thanks for reporting the issue!

I don't know yet why this is broken, there's probably something wrong with `CRYSTAL_PATH`, but I need to investigate this deeper.

As a work around you can do `ic myclass.cr`, but this doesn't open a RELP after executing the file.

**Comment by I3oris** [comment]
Find out what's going on!: it's not at all a problem with `CRYSTAL_PATH`, I have modified the location of the top level code in order display correct errors location and allow pry at top level (in https://github.com/I3oris/ic/commit/7341688a8a16db3517e2f51ed7094f836d6fe101). But I set an expanded location to nil instead of an empty string, and that causes the files to not be found.

I will push the fix soon.
